### ISSUE TITLE
Setting Coding Scheme to ------- generates error

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/sati#22]
The coding scheme now defaults to Wang, which is cool, but manually setting the coding scheme to the "undefined" option (`--------`), for whatever reason, leads to a Django error page when the item is saved, with the following unhelpful message:

`No such file or directory: '[SATI_ROOT]/sati/items/schemas/.json'`

Probably this field should be set to required so that attempting to use the "undefined" option generates an in-band `This field is required.` message, as happens with most other input fields.

**Comment by simonwiles** [comment]
It's the `coding` field that's raising the exception, not the `coding_schema` field itself (which is required and does generate the "This field is required" message if no exception is raised beforehand).  There are two fixes for this: 1) the `CodingField` (or, rather, the `JSONSchemaField` it inherits from) should raise a `ValidationError` if the schema can't be loaded from disk; and 2) the widget for the `coding_schema` field shouldn't allow selecting "-----" anyway :)  PR incoming.
