### ISSUE TITLE
Should it be possible to add a coding via the interface with no attributes checked?

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/sati#23]
This is currently allowed. It's not obvious why one would want to do this via the interface; not choosing an attribute is more likely to be a mistake that perhaps should be flagged via an in-band error message noting that at least one attribute must be selected.

In the case of bulk uploads, though, there probably could be a scenario in which a coding is created but not filled in, with the intention that someone would fill it in later via the interface. But in that (hypothetical) case, the initial coding creation wouldn't be done via the interface, so this question wouldn't really apply.

**Comment by simonwiles** [comment]
Yeah, I considered this.  It's possible, of course, that a coding might be `false` for all dimensions, but yes it is obviously _far_ more likely to just be a mistake.  I'll ask the GSE team what they think.  I suppose a little JS client-side validation and an "are you sure?" dialogue would be appropriate?

**Comment by broadwell** [comment]
Yes I think there's no need to change the current behavior without conferring with the GSE team. But an "are you sure" dialog would be a good way to handle it, I think.

**Comment by simonwiles** [comment]
GSE team (Hsiaolin and Chao) agree that empty coding forms should be valid but warned against.  PR incoming.
